version: '3.9'
services:
  api:
    image: ir1401/hackathon-api:latest
    container_name: hackathon-api
    restart: 'unless-stopped'
    environment:
      - "DB_CONNECTION=$DB_CONNECTION"
    expose:
      - '8080:8082'
  web:
    image: ir1401/hackathon-ui:latest
    container_name: hackathon-ui
    restart: 'unless-stopped'
    ports:
      - '8082:8082'